### ISSUE TITLE
Import/Install issues with Python

### ISSUE THREAD

**Issue by beneshed** [ros/geometry#119]
Trying to run the basic tf/odom python ros tutorials and I can't seem to even import tf

I've done the following

```
 sudo apt-get install ros-indigo-geometry-experimental ros-indigo-geometry ros-indigo-geometry-msgs
```

Before cloning the git repo and running 

```
python setup.py install
```

```
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tf
```

And after 

```
vagrant@vagrant-ubuntu-trusty-64:~/ros_workspace$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tf/__init__.py", line 28, in <module>
    from _tf import *
ImportError: No module named _tf
```

What am I doing wrong?

**Comment by tfoote** [comment]
You need to build your workspace using catkin_make or catkin_make_isolated. Please ask on answers.ros.org with full details how to reproduce your workspace and all the commands that you ran. You generally should not be invoking setup.py directly.
