### ISSUE TITLE
cannot import tf_conversions in Python 

### ISSUE THREAD

**Issue by ninafiona** [ros/geometry#215]
Ubuntu 18.04, ros melodic, Python 2.7

I tried to import tf_conversions, but got the following error:

```
import tf_conversions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf_conversions/__init__.py", line 30, in <module>
    from .posemath import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf_conversions/posemath.py", line 34, in <module>
    from PyKDL import *
ImportError: No module named sip
```

I tried to build orocos-kdl with python-orocos-kdl from source, but it doesn't work if I also have another version installed from ros-orocos-kdl (I can only build and install when ros-orocos-kdl isn't installed). 

Similar issue here: https://github.com/orocos/orocos_kinematics_dynamics/issues/287

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as of today, May 31st 2025. I am archiving this repository because:

* it only supports ROS 1
* it isn't needed anymore in ROS 2

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
