### ISSUE TITLE
listener.py can't find sensor_msgs

### ISSUE THREAD

**Issue by bit-pirate** [ros/geometry#28]
... although the package is installed.

This is a new bug - saw it today for the first time, when trying to launch the turtlebot simulation:

```
$ roslaunch turtlebot_gazebo turtlebot_empty_world.launch

[...]

Traceback (most recent call last):
  File "/opt/kobuki_workspace/catkin_ws/install/lib/gazebo_ros/spawn_model", line 31, in <module>
    import tf.transformations as tft
  File "/opt/ros/hydro/lib/python2.7/dist-packages/tf/__init__.py", line 29, in <module>
    from listener import TransformListener, TransformerROS
  File "/opt/ros/hydro/lib/python2.7/dist-packages/tf/listener.py", line 39, in <module>
    import sensor_msgs.msg
ImportError: No module named sensor_msgs.msg

[...]

$ rospack find sensor_msgs 
/opt/ros/hydro/share/sensor_msgs
```

Strange bug ...

**Comment by bit-pirate** [comment]
Ignore. This bug comes from here: https://github.com/ros/common_msgs/commit/c62b5fe374a3d5098d321eb9c51887048b29f2fc
